### ISSUE TITLE
reviewers.py: error: unrecognized arguments: --path=./

### ISSUE THREAD

**Issue by gergelypolonkai** [albertyw/git-reviewers#23]
Right after installation, I get this error message:

    $ git reviewers
    usage: reviewers.py [-h] [-v] [-i IGNORE] [-c]
    reviewers.py: error: unrecognized arguments: --path=./

Indeed, the `--path` argument is not listed in the `--help` output, neither can be found in the code. If I remove the `--path=${GIT_PREFIX:-./}`, it works just fine.

**Comment by albertyw** [comment]
Should be fixed in a5e165fde25bd3ab88dcb4538d006696aee5448a
