### ISSUE TITLE
make base branch configurable

### ISSUE THREAD

**Issue by aspiers** [albertyw/git-reviewers#44]
Currently the base branch which changes are compared against is hardcoded to `master`:

https://github.com/albertyw/git-reviewers/blob/014e645407ea986ab18fa39da43e3b1f5745cde4/git_reviewers/reviewers.py#L126-L128

This is an issue because in many scenarios, git reviewers can be run on a branch which would be based on another branch such as `origin/master`.  If that diverges from `master` then the whole algorithm is not based on the right changes, and in the worst case it results in terrible performance as seen in #40.

So ideally this should be configurable via a CLI option, since the base branch will vary per repo.  However a good first start would be to default to comparing against the branch configured as `$mybranch`'s upstream branch by the `branch.$mybranch.remote` and `branch.$mybranch.merge` configuration options.

**Comment by albertyw** [comment]
Fixed in cad0fbe
